### ISSUE TITLE
Cookie问题

### ISSUE THREAD

**Issue by just2022try** [LeonX86/Music-copartner-sverless#2]
感谢大佬分享。
经过尝试，因为自己比较菜，遇到一些问题，写这里给以后的朋友避个坑。
① cookie里面的__csrf字段不可缺。
② cookie抓取时候务必开无痕模式，方能获取到所有的值，直接随便找个请求头的cookie贴上就可完美运行。

再次谢谢老哥的云函数版本，腾讯云阿里云函数均可运行。

**Comment by LeonX86** [comment]
✨大佬谦虚了，承让
我自己抓cookie的时候已经是400多天前了，然后那个时候也没开无痕模式，到现在也没掉过。网易还是很良心滴
